Pizzazz::Program
static void Pizzazz.Program.Main(string[] args)
References Pizzazz.Program.DurePizza, Pizzazz.Program.GoedkopePizza, PizzazzLibrary.Implementation.PizzaMargheritaFactory.Instance, Pizzazz.Program.PizzaMargheritaMetSalami, PizzazzLibrary.Implementation.PizzaMargheritaFactory.PreparePizza.
static void Pizzazz.Program.GoedkopePizza()
References Pizzazz.PizzaDelivery.DeliverPizza, Pizzazz.PizzaDelivery.factory, PizzazzLibrary.Implementation.PizzaMargheritaFactory.Instance.
Referenced by Pizzazz.Program.Main.
static void Pizzazz.Program.DurePizza()
Referenced by Pizzazz.Program.Main.
static void Pizzazz.Program.PizzaMargheritaMetSalami()
References PizzazzLibrary.Implementation.PizzaMargheritaFactory.Instance, PizzazzLibrary.Implementation.PizzaMargheritaFactory.PreparePizza.
Referenced by Pizzazz.Program.Main.